---
- name: Pre-reqs for ansible to run
  hosts: all
  gather_facts: false
  become: yes
  pre_tasks:
    - raw: test -e /usr/bin/python || ( yum -y update && yum install -y python-minimal )

- name: Build Tableau Linux Server
  hosts: all
  become: true
  tasks:

  - name: Create tableau_srv user
    user:
      name: tableau_srv

  - name: Create .ssh directory for tableau_srv user
    file:
      path: /home/tableau_srv/.ssh
      state: directory
      mode: 0700
      owner: tableau_srv


  - name: Create scripts directory for tableau_srv user c/w all files
    copy:
      src: tableau-scripts/
      dest: /home/tableau_srv/scripts
      owner: tableau_srv
      group: tableau_srv
      mode: 0544

  - name: Ensure Tableau backup to S3 log file for tableau_srv user exists
    copy:
      content: ""
      dest: /var/log/last-tab-backup-to-s3.log
      force: no
      owner: tableau_srv
      group: tableau_srv
      mode: 0644

  - name: Create cronjob to run Tableau to S3 backup script every day at 7PM
    cron:
      name: Tableau to S3 backup
      user: tableau_srv
      minute: 0
      hour: 19
      job: . $HOME/.bashrc; /home/tableau_srv/scripts/tableau-backup.sh

  - name: Yum Install Pre Dependencies
    yum: name={{ item }}
    with_items:
      - epel-release
      - gcc
      - pcre-devel
      - openssl-devel
      - zlib-devel
      - wget
    become: true

  - name: Yum Install Dependencies
    yum: name={{ item }}
    with_items:
      - git
      - cloud-utils
    become: true

  - name: Install Python 3.7
    unarchive:
     src: https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tgz
     dest: /usr/src
     remote_src: yes
    become: true

  - name: Configure Python 3.7
    shell: ./configure --enable-optimizations
    args:
      chdir: /usr/src/Python-3.7.2
      creates: /usr/src/Python-3.7.2/Modules
    become: true

  - name: Pip Install Dependencies
    pip: 'name={{ item }}'
    executable: pip3.7
    with_items:
      - AWSCLI
    become: true

  - name: GET Tableau files from DQ-config-bucket
    shell: aws s3 cp s3://dq-config-bucket/dq-tableau-linux/gold-master /tmp/install --recursive

  - name: Yum Install other packages (Tableau stuff from config_bucket & zip/unzip)
    yum:
      name:
        - /tmp/install/tableau-postgresql-odbc-gold-master.x86_64.rpm
        - /tmp/install/tableau-server-gold-master.x86_64.rpm
        - /tmp/install/tableau-tabcmd-gold-master.noarch.rpm
        - zip
        - unzip

  - name: Download cloudwatch logs agent
    get_url:
      url: https://s3.amazonaws.com//aws-cloudwatch/downloads/latest/awslogs-agent-setup.py
      dest: /tmp/awslogs-agent-setup.py
      mode: "+x"

  - name: GET Cloudwatch logs config from DQ-config-bucket
    shell: aws s3 cp s3://dq-config-bucket/dq-tableau-linux/cwlogs.conf /tmp

  - name: Install cloudwatch log agent
    environment:
      LC_ALL: C
    shell: /tmp/awslogs-agent-setup.py --region eu-west-2 --non-interactive -c /tmp/cwlogs.conf
    args:
      creates: /var/awslogs/etc/aws.conf

  - name: Copy cloudwatch logs starter
    copy:
      src: scripts/startcloudwatchlogs.sh
      dest: /usr/bin/startcloudwatchlogs.sh
      owner: root
      group: root
      mode: 0755

  - name: Make Cron Job to start awslogs with right region
    cron:
      name: Start awslogs
      special_time: reboot
      job: /usr/bin/startcloudwatchlogs.sh

  - name: Set DNS Resolver Options
    blockinfile:
      path: /etc/sysconfig/network
      block: |
        RES_OPTIONS="rotate timeout:1 attempts:1"

  - name: Secure sshd_config
    lineinfile: dest=/etc/ssh/sshd_config
                regexp="^PermitRootLogin"
                line="PermitRootLogin no"
                state=present
  - lineinfile: dest=/etc/ssh/sshd_config
                regexp="^PasswordAuthentication"
                line="PasswordAuthentication no"
                state=present
  - lineinfile: dest=/etc/ssh/sshd_config
                regexp="^X11Forwarding"
                line="X11Forwarding no"
                state=present
